name: Build Docker Image

on:
  push:
    branches: [fix-recent-languages]
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/hxreborn/metrics:latest .

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/hxreborn/metrics:latest
